version: "3.9"
services: 
  front:
    build: ./test-frontend
    container_name: front
    ports:
      - 80:3001
    depends_on:
      - back
    command: sh -c "cd /app; rm -rf node_modules; npm install; npm run build; npm run serve;"
  back: 
    build: ./test-backend
    container_name: back
    ports:
      - 3000:3000
    command: sh -c "cd /app; rm -rf node_modules; npm install; npm run build; npm run start;"
